[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/assets/*.woff2"
  [headers.values]
    Content-Type = "font/woff2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200