blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions and Help
    url: https://github.com/eshanized/devfolio/discussions
    about: Please use the discussions forum for questions and help
  - name: 💬 Community Discord
    url: https://discord.gg/your-discord-invite
    about: Join our Discord community for real-time discussions
  - name: 📖 Documentation
    url: https://github.com/eshanized/devfolio#readme
    about: Check out our documentation before creating an issue