name: 💡 Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out the form below with as much detail as possible.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please ensure you have completed these steps before submitting a feature request
      options:
        - label: I have searched the existing issues to make sure this feature hasn't been requested before
          required: true
        - label: I have read the documentation to ensure this feature doesn't already exist
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: I would like to see [...]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        Alternative 1: [...]
        Alternative 2: [...]

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits would this feature bring to users?
      placeholder: This feature would help users to [...]
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How would you rate the impact of this feature?
      options:
        - Critical (Must have)
        - High (Important)
        - Medium (Nice to have)
        - Low (Could wait)
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Details
      description: If you have any ideas about how this could be implemented, please share them
      placeholder: This could be implemented by [...]

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here